<a href="https://colab.research.google.com/github/adasko-a/datascience_bootcamp/blob/main/01_wprowadzenie/%C5%82%C4%85czenie_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import numpy as np


def fetch_financial_data(company='AMZN'):
    """
    This function fetches stock market quotations.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

apple = fetch_financial_data('AAPL')
amazon = fetch_financial_data('AMZN')
google = fetch_financial_data('GOOGL')
uber = fetch_financial_data('UBER')

In [24]:
google.head()

               Open      High       Low   Close    Volume
Date
2026-03-20  305.460  306.0000  298.2700  301.00  44364080
2026-03-19  304.005  308.0600  302.3500  307.13  25075831
2026-03-18  309.270  312.4700  306.9320  307.69  20009815
2026-03-17  305.860  311.4200  305.5000  310.92  21955171
2026-03-16  304.350  306.4886  303.0201  305.56  23519709

In [7]:
uber.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1256 entries, 2026-03-20 to 2021-03-22
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    1256 non-null   float64
 1   High    1256 non-null   float64
 2   Low     1256 non-null   float64
 3   Close   1256 non-null   float64
 4   Volume  1256 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 58.9 KB

In [43]:
apple.columns = [col if 'apple_'in col else 'apple_'+ col.lower() for col in apple.columns]
amazon.columns = [col if 'amazon_'in col else'amazon_'+ col.lower() for col in amazon.columns]
google.columns = [col if 'google_'in col else'google_'+ col.lower() for col in google.columns]
uber.columns = [col if 'uber_'in col else'uber_'+ col.lower() for col in uber.columns]
google.columns

Index(['google_open', 'google_high', 'google_low', 'google_close',
       'google_volume'],
      dtype='object')

In [44]:
df = pd.concat(objs=[apple, amazon, google, uber], axis=1)

In [45]:
df.head()

,apple_open,apple_high,apple_low,apple_close,apple_volume,amazon_open,amazon_high,amazon_low,amazon_close,amazon_volume,google_open,google_high,google_low,google_close,google_volume,uber_open,uber_high,uber_low,uber_close,uber_volume
Date,,,,,,,,,,,,,,,,,,,,
2026-03-20,247.975,249.1999,246.00,247.99,88331081,207.400,207.5400,204.316,205.37,63694603,305.460,306.0000,298.2700,301.00,44364080,74.98,74.980,73.04,73.89,26161241
2026-03-19,249.400,251.8300,247.30,248.96,34864082,207.060,209.1200,206.050,208.76,36440622,304.005,308.0600,302.3500,307.13,25075831,76.70,77.845,75.32,75.34,13791622
2026-03-18,252.625,254.9400,249.00,249.94,35757874,213.925,215.1401,208.825,209.87,37846642,309.270,312.4700,306.9320,307.69,20009815,77.43,77.680,76.48,76.66,13692695
2026-03-17,252.955,255.1300,252.18,254.23,32361607,212.820,215.7000,212.430,215.20,44969943,305.860,311.4200,305.5000,310.92,21955171,77.39,79.230,77.31,77.79,33146083
2026-03-16,252.105,253.8850,249.88,252.82,32074210,208.350,212.7240,207.445,211.74,42209316,304.350,306.4886,303.0201,305.56,23519709,74.00,75.380,74.00,74.66,15997278

In [48]:
pd.set_option('display.float_format',lambda x: f' {x:.2f}')

In [49]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
apple_open,1256.00,185.14,41.76,116.55,149.24,175.34,219.44,286.20
apple_high,1256.00,187.14,42.05,117.39,151.31,177.21,221.80,288.62
apple_low,1256.00,183.33,41.42,115.88,147.63,173.98,216.68,283.30
apple_close,1256.00,185.32,41.73,116.90,149.32,175.64,219.75,286.19
apple_volume,1256.00,68010111.14,28989195.47,17910574.00,47472288.50,61069156.50,81581939.75,320473399.00
amazon_open,1256.00,166.13,42.19,82.80,132.11,168.58,197.49,255.36
amazon_high,1256.00,168.08,42.35,83.48,133.66,170.54,199.27,258.60
amazon_low,1256.00,164.02,41.89,81.43,130.48,166.59,193.92,252.90
amazon_close,1256.00,166.10,42.13,81.82,132.12,169.00,196.72,254.00
amazon_volume,1256.00,56670987.06,27032431.91,11420543.00,39426993.25,50579562.00,66273045.00,272661720.00
google_open,1256.00,155.46,56.37,85.09,118.81,139.73,171.92,347.34
google_high,1256.00,157.27,57.01,86.21,119.89,141.23,173.93,349.00
google_low,1256.00,153.71,55.61,83.04,117.83,138.44,170.07,337.47
google_close,1256.00,155.55,56.38,83.13,118.74,139.89,171.86,343.69
google_volume,1256.00,32289703.66,13638560.93,9736609.00,23580263.25,28978746.50,36635166.25,127747554.00
uber_open,1256.00,55.98,21.92,20.37,36.65,51.01,73.98,100.13
uber_high,1256.00,56.90,22.12,21.13,37.59,51.67,75.28,101.99
uber_low,1256.00,55.03,21.66,19.89,35.63,50.30,72.75,98.58
uber_close,1256.00,55.96,21.89,20.46,36.79,50.83,73.96,100.10
uber_volume,1256.00,23442973.43,16078547.59,4310663.00,15411725.50,19856349.00,27313234.00,364261230.00

In [50]:
df.corr()

,apple_open,apple_high,apple_low,apple_close,apple_volume,amazon_open,amazon_high,amazon_low,amazon_close,amazon_volume,google_open,google_high,google_low,google_close,google_volume,uber_open,uber_high,uber_low,uber_close,uber_volume
apple_open,1.00,1.00,1.00,1.00,-0.47,0.76,0.76,0.76,0.76,-0.40,0.87,0.87,0.87,0.87,-0.00,0.79,0.79,0.79,0.79,-0.12
apple_high,1.00,1.00,1.00,1.00,-0.45,0.76,0.77,0.76,0.76,-0.39,0.87,0.87,0.87,0.87,0.00,0.78,0.79,0.79,0.79,-0.12
apple_low,1.00,1.00,1.00,1.00,-0.48,0.77,0.77,0.76,0.76,-0.41,0.87,0.87,0.87,0.87,-0.01,0.79,0.79,0.79,0.79,-0.12
apple_close,1.00,1.00,1.00,1.00,-0.47,0.76,0.77,0.76,0.76,-0.40,0.87,0.87,0.87,0.87,-0.00,0.79,0.79,0.79,0.79,-0.12
apple_volume,-0.47,-0.45,-0.48,-0.47,1.00,-0.29,-0.29,-0.30,-0.29,0.57,-0.35,-0.34,-0.35,-0.34,0.27,-0.42,-0.42,-0.42,-0.42,0.24
amazon_open,0.76,0.76,0.77,0.76,-0.29,1.00,1.00,1.00,1.00,-0.39,0.81,0.81,0.81,0.81,-0.04,0.87,0.87,0.87,0.87,-0.13
amazon_high,0.76,0.77,0.77,0.77,-0.29,1.00,1.00,1.00,1.00,-0.38,0.81,0.81,0.82,0.81,-0.03,0.87,0.87,0.87,0.87,-0.13
amazon_low,0.76,0.76,0.76,0.76,-0.30,1.00,1.00,1.00,1.00,-0.40,0.81,0.81,0.81,0.81,-0.05,0.87,0.87,0.87,0.87,-0.14
amazon_close,0.76,0.76,0.76,0.76,-0.29,1.00,1.00,1.00,1.00,-0.39,0.81,0.81,0.81,0.81,-0.04,0.87,0.87,0.87,0.87,-0.13
amazon_volume,-0.40,-0.39,-0.41,-0.40,0.57,-0.39,-0.38,-0.40,-0.39,1.00,-0.30,-0.30,-0.31,-0.30,0.38,-0.45,-0.45,-0.45,-0.45,0.28
google_open,0.87,0.87,0.87,0.87,-0.35,0.81,0.81,0.81,0.81,-0.30,1.00,1.00,1.00,1.00,0.02,0.74,0.74,0.74,0.74,-0.12
google_high,0.87,0.87,0.87,0.87,-0.34,0.81,0.81,0.81,0.81,-0.30,1.00,1.00,1.00,1.00,0.03,0.74,0.74,0.74,0.74,-0.12
google_low,0.87,0.87,0.87,0.87,-0.35,0.81,0.82,0.81,0.81,-0.31,1.00,1.00,1.00,1.00,0.01,0.74,0.74,0.74,0.74,-0.12
google_close,0.87,0.87,0.87,0.87,-0.34,0.81,0.81,0.81,0.81,-0.30,1.00,1.00,1.00,1.00,0.02,0.74,0.74,0.74,0.74,-0.12
google_volume,-0.00,0.00,-0.01,-0.00,0.27,-0.04,-0.03,-0.05,-0.04,0.38,0.02,0.03,0.01,0.02,1.00,-0.01,-0.01,-0.02,-0.01,0.20
uber_open,0.79,0.78,0.79,0.79,-0.42,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.74,0.74,-0.01,1.00,1.00,1.00,1.00,-0.21
uber_high,0.79,0.79,0.79,0.79,-0.42,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.74,0.74,-0.01,1.00,1.00,1.00,1.00,-0.21
uber_low,0.79,0.79,0.79,0.79,-0.42,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.74,0.74,-0.02,1.00,1.00,1.00,1.00,-0.22
uber_close,0.79,0.79,0.79,0.79,-0.42,0.87,0.87,0.87,0.87,-0.45,0.74,0.74,0.74,0.74,-0.01,1.00,1.00,1.00,1.00,-0.21
uber_volume,-0.12,-0.12,-0.12,-0.12,0.24,-0.13,-0.13,-0.14,-0.13,0.28,-0.12,-0.12,-0.12,-0.12,0.20,-0.21,-0.21,-0.22,-0.21,1.00

In [51]:
closes = [col for col in df.columns if col.endswith('close')]
closes

['apple_close', 'amazon_close', 'google_close', 'uber_close']

In [52]:
df[closes].corr()

              apple_close  amazon_close  google_close  uber_close
apple_close          1.00          0.76          0.87        0.79
amazon_close         0.76          1.00          0.81        0.87
google_close         0.87          0.81          1.00        0.74
uber_close           0.79          0.87          0.74        1.00

#df.append()

In [53]:
uber_6 = uber[uber.index.month == 6]
uber_6

            uber_open  uber_high  uber_low  uber_close  uber_volume
Date
2025-06-30      91.69      93.39     91.52       93.30     16155270
2025-06-27      91.86      92.51     89.97       91.53     24731168
2025-06-26      91.30      94.38     90.88       93.12     23657765
2025-06-25      91.56      92.89     90.60       90.90     17400840
2025-06-24      87.99      92.48     87.91       91.65     38925080
...               ...        ...       ...         ...          ...
2021-06-07      50.49      51.22     49.75       50.76     16466233
2021-06-04      49.56      50.22     49.07       50.18     10409827
2021-06-03      50.43      50.50     48.53       48.70     14712859
2021-06-02      51.19      51.41     50.55       50.79     13484205
2021-06-01      51.62      51.66     49.84       50.98     16583752

[103 rows x 5 columns]

In [55]:
uber_7 = uber[uber.index.month == 7]

uber_6.append(uber_7)
uber_6
# nie działa dla wyzszych wersji pandas

AttributeError: 'DataFrame' object has no attribute 'append'